name: Deploy

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Client Dependencies
        run: |
          cd client/
          npm i
      - name: Build Client Files
        run: |
          cd client/
          npm run build
      - name: Install Server Dependencies
        run: |
          cd server/
          npm i
      - name: Set .env File Server
        run: |
          cd server/
          touch .env
          cat << EOF >> .env	
          ${{ secrets.SERVER_ENV }}
      - name: Build Server Files
        run: |
          cd server/
          tsc   
      - name: Make Tar File
        run: tar -cpvzf ./$GITHUB_SHA.tgz *
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            ./$GITHUB_SHA.tgz s3://cashbook-build/build/$GITHUB_SHA.tgz
            
      - name: Code Deploy
        run: aws deploy create-deployment --application-name cashbook --file-exists-behavior OVERWRITE --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name cashbook --s3-location bucket=cashbook-build,bundleType=tgz,key=build/$GITHUB_SHA.tgz